study_prefix = "quality"

[sql_config]
file_names = [
    "metadata.sql",
]

[table_builder_config]
file_names = [
    "c_pt_count/c_pt_count.py",
    "c_pt_deceased_count/c_pt_deceased_count.py",
    "c_resource_count/c_resource_count.py",
    "c_resources_per_pt/c_resources_per_pt.py",
    "c_term_coverage/c_term_coverage.py",
    "c_us_core_v4_count/c_us_core_v4_count.py",
    "q_ref_target_pop/q_ref_target_pop.py",
    "q_ref_target_valid/q_ref_target_valid.py",
    "q_term_use/q_term_use.py",
    "q_valid_us_core_v4/q_valid_us_core_v4.py",
]

[export_config]
export_list = [
    "quality__count_c_pt_count",
    "quality__count_c_pt_deceased_count",
    "quality__count_c_resource_count_allergyintolerance_month",
    "quality__count_c_resource_count_allergyintolerance_year",
    "quality__count_c_resource_count_condition_month",
    "quality__count_c_resource_count_condition_year",
    "quality__count_c_resource_count_device_all",
    "quality__count_c_resource_count_diagnosticreport_month",
    "quality__count_c_resource_count_diagnosticreport_year",
    "quality__count_c_resource_count_documentreference_month",
    "quality__count_c_resource_count_documentreference_year",
    "quality__count_c_resource_count_encounter_month",
    "quality__count_c_resource_count_encounter_year",
    "quality__count_c_resource_count_immunization_month",
    "quality__count_c_resource_count_immunization_year",
    "quality__count_c_resource_count_medication_all",
    "quality__count_c_resource_count_medicationrequest_month",
    "quality__count_c_resource_count_medicationrequest_year",
    "quality__count_c_resource_count_observation_month",
    "quality__count_c_resource_count_observation_year",
    "quality__count_c_resource_count_patient_all",
    "quality__count_c_resource_count_procedure_month",
    "quality__count_c_resource_count_procedure_year",
    "quality__count_c_term_coverage_allergyintolerance_code",
    "quality__count_c_term_coverage_condition_code",
    "quality__count_c_term_coverage_device_type",
    "quality__count_c_term_coverage_diagnosticreport_code",
    "quality__count_c_term_coverage_documentreference_type",
    "quality__count_c_term_coverage_encounter_class",
    "quality__count_c_term_coverage_encounter_type",
    "quality__count_c_term_coverage_immunization_vaccinecode",
    "quality__count_c_term_coverage_medication_code",
    "quality__count_c_term_coverage_medicationrequest_medicationcodeableconcept",
    "quality__count_c_term_coverage_observation_code",
    "quality__count_c_term_coverage_observation_valuecodeableconcept",
    "quality__count_c_term_coverage_procedure_code",
    "quality__count_c_us_core_v4_count_allergyintolerance",
    "quality__count_c_us_core_v4_count_condition",
    "quality__count_c_us_core_v4_count_diagnosticreport_note",
    "quality__count_c_us_core_v4_count_documentreference",
    "quality__count_c_us_core_v4_count_encounter",
    "quality__count_c_us_core_v4_count_immunization",
    "quality__count_c_us_core_v4_count_medication",
    "quality__count_c_us_core_v4_count_medicationrequest",
    "quality__count_c_us_core_v4_count_observation_laboratory",
    "quality__count_c_us_core_v4_count_observation_smoking_status",
    "quality__count_c_us_core_v4_count_observation_vital_signs",
    "quality__count_c_us_core_v4_count_patient",
    "quality__count_c_us_core_v4_count_procedure",
]
