study_prefix = "quality"

[sql_config]
file_names = [
    "c_pt_deceased_count.sql",
    "metadata.sql",
]

[table_builder_config]
file_names = [
    "c_resource_count.py",
    "q_ref_target_pop.py",
    "q_ref_target_valid.py",
    "q_term_use.py",
]

[export_config]
export_list = [
    "quality__count_c_pt_deceased_count",
    "quality__count_c_resource_count_allergyintolerance_month",
    "quality__count_c_resource_count_allergyintolerance_year",
    "quality__count_c_resource_count_condition_month",
    "quality__count_c_resource_count_condition_year",
    "quality__count_c_resource_count_device_all",
    "quality__count_c_resource_count_documentreference_month",
    "quality__count_c_resource_count_documentreference_year",
    "quality__count_c_resource_count_encounter_month",
    "quality__count_c_resource_count_encounter_year",
    "quality__count_c_resource_count_immunization_month",
    "quality__count_c_resource_count_immunization_year",
    "quality__count_c_resource_count_medication_all",
    "quality__count_c_resource_count_medicationrequest_month",
    "quality__count_c_resource_count_medicationrequest_year",
    "quality__count_c_resource_count_observation_month",
    "quality__count_c_resource_count_observation_year",
    "quality__count_c_resource_count_patient_all",
    "quality__count_c_resource_count_procedure_month",
    "quality__count_c_resource_count_procedure_year",
]
